apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: python-template
  title: Python flask template
  description: Provisions a minimalistic flask application
spec:
  owner: development
  type: service

  parameters:
    - title: Basic Information
      required:
        - component_id
      properties:
        component_id:
          title: Component name
          type: string
          description: Provide a component (microservice) name
          pattern: '^([a-zA-Z][a-zA-Z0-9]*)(-[a-zA-Z0-9]+)*$'

    - title: Deployment Settings
      required:
        - environment
      properties:
        environment:
          title: Environment
          type: string
          description: The environment where this component will be deployed
          enum:
            - dev
            - prod
        any:
          title: Any Option
          type: boolean
          description: Set to true to enable the 'any' feature
          default: false

    - title: Feature Options
      properties:
        enable_logging:
          title: Enable Logging
          type: boolean
          description: Adds structured logging to your Flask app
        enable_monitoring:
          title: Enable Monitoring
          type: boolean
          description: Integrates basic health and metrics endpoints
        include_dockerfile:
          title: Include Dockerfile
          type: boolean
          description: Adds a Dockerfile for containerization
        include_gitignore:
          title: Include .gitignore
          type: boolean
          description: Adds a standard Python .gitignore file
        use_postgresql:
          title: Use PostgreSQL
          type: boolean
          description: Adds PostgreSQL client and connection config
        use_sqlite:
          title: Use SQLite
          type: boolean
          description: Adds SQLite for local development
        enable_authentication:
          title: Enable Authentication
          type: boolean
          description: Adds JWT-based auth middleware
        enable_cors:
          title: Enable CORS
          type: boolean
          description: Adds CORS headers for cross-origin requests
        add_swagger:
          title: Add Swagger UI
          type: boolean
          description: Auto-generates Swagger documentation
        add_unit_tests:
          title: Add Unit Tests
          type: boolean
          description: Adds a basic Pytest test suite
        add_ci_pipeline:
          title: Add CI Pipeline
          type: boolean
          description: Adds GitHub Actions for lint/test
        enable_rate_limiting:
          title: Enable Rate Limiting
          type: boolean
          description: Adds Flask-Limiter to prevent abuse
        enable_request_id:
          title: Add Request ID Middleware
          type: boolean
          description: Generates unique IDs for tracking each request
        include_env_file:
          title: Include .env Template
          type: boolean
          description: Adds a `.env` example file
        enable_https_redirect:
          title: Force HTTPS Redirect
          type: boolean
          description: Redirect all HTTP traffic to HTTPS
      ui:
        layout:
          - [enable_logging, enable_monitoring, include_dockerfile]
          - [include_gitignore, use_postgresql, use_sqlite]
          - [enable_authentication, enable_cors, add_swagger]
          - [add_unit_tests, add_ci_pipeline, enable_rate_limiting]
          - [enable_request_id, include_env_file, enable_https_redirect]

  steps:
    - id: fetch-base
      name: Fetch Base
      action: fetch:template
      input:
        url: ./template
        values:
          app_name: ${{ parameters.component_id }}
          app_env: ${{ parameters.environment }}
          use_any: ${{ parameters.any }}
          features:
            logging: ${{ parameters.enable_logging }}
            monitoring: ${{ parameters.enable_monitoring }}
            dockerfile: ${{ parameters.include_dockerfile }}
            gitignore: ${{ parameters.include_gitignore }}
            postgresql: ${{ parameters.use_postgresql }}
            sqlite: ${{ parameters.use_sqlite }}
            auth: ${{ parameters.enable_authentication }}
            cors: ${{ parameters.enable_cors }}
            swagger: ${{ parameters.add_swagger }}
            tests: ${{ parameters.add_unit_tests }}
            ci: ${{ parameters.add_ci_pipeline }}
            rate_limit: ${{ parameters.enable_rate_limiting }}
            request_id: ${{ parameters.enable_request_id }}
            env_file: ${{ parameters.include_env_file }}
            https_redirect: ${{ parameters.enable_https_redirect }}

    - id: publish
      name: Publish
      action: publish:github
      input:
        allowedHosts:
          - github.com
        description: This is ${{ parameters.component_id }}
        repoUrl: github.com?owner=swastika-kar-2003&repo=${{parameters.component_id}}
        protectDefaultBranch: false
        repoVisibility: public

    - id: register
      name: Register
      action: catalog:register
      input:
        repoContentsUrl: ${{ steps['publish'].output.repoContentsUrl }}
        catalogInfoPath: "/catalog-info.yaml"

  output:
    links:
      - title: Repository
        url: ${{ steps['publish'].output.remoteUrl }}
