apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: ${{ values.app_name }}
  description: python app that displays time deployed on ${{ values.app_env }}
  annotations:
    github.com/project-slug: swas-kar/${{ values.app_name }}
    backstage.io/techdocs-ref: dir:.
spec:
  type: service
  owner: development
  lifecycle: experimental
