apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: ${{ values.app_name }}
  description: python app that displays time of name ${{ values.app_name }}
  annotations:
    github.com/project-slug: swastika-kar-2003/${{ values.app_name }}
    backstage.io/techdocs-ref: dir:.
spec:
  type: service
  owner: development
  lifecycle: experimental

